import eslintReact from '@eslint-react/eslint-plugin';
import eslint from '@eslint/js';
import eslintImport from 'eslint-plugin-import';
import eslintReactHooks from 'eslint-plugin-react-hooks';
import sortKeysFix from 'eslint-plugin-sort-keys-fix';
import { defineConfig, globalIgnores } from 'eslint/config';
import eslintTS from 'typescript-eslint';
import eslintReactPlugin from 'eslint-plugin-react';

export default defineConfig([
    // ignore generated gRPC files
    globalIgnores(['server/gRPC/generated/']),
    // define configuration
    {
        extends: [
            eslint.configs.all,
            eslintTS.configs.all,
            eslintImport.flatConfigs.recommended,
            eslintImport.flatConfigs.errors,
            eslintImport.flatConfigs.react,
            eslintImport.flatConfigs.warnings,
            eslintImport.flatConfigs.typescript,
            eslintReact.configs.all,
            eslintReactHooks.configs.flat['recommended-latest'],
            eslintReactPlugin.configs.flat.all,
        ],
        languageOptions: {
            ecmaVersion: 'latest',
            parser: eslintTS.parser,
            parserOptions: {
                ecmaFeatures: { jsx: true },
                project: ['./tsconfig.json', './tsconfig.eslint.json'],
            },
            sourceType: 'module',
        },
        plugins: {
            'react-hooks': eslintReactHooks,
            'sort-keys-fix': sortKeysFix,
        },
        rules: {
            '@eslint-react/avoid-shorthand-fragment': 'off',
            '@eslint-react/hooks-extra/no-direct-set-state-in-use-effect':
                'off',
            '@eslint-react/hooks-extra/no-unnecessary-use-prefix': 'off',
            '@eslint-react/jsx-no-iife': 'off',
            '@eslint-react/naming-convention/filename': 'off',
            '@eslint-react/naming-convention/filename-extension': 'off',
            '@eslint-react/no-array-index-key': 'off',
            '@eslint-react/no-children-to-array': 'off',
            '@eslint-react/no-class-component': 'off',
            '@eslint-react/no-complex-conditional-rendering': 'off',
            '@eslint-react/prefer-destructuring-assignment': 'off',
            '@typescript-eslint/array-type': [
                'error',
                { default: 'array-simple' },
            ],
            '@typescript-eslint/class-methods-use-this': 'off',
            '@typescript-eslint/consistent-type-definitions': 'off',
            '@typescript-eslint/explicit-function-return-type': 'off',
            '@typescript-eslint/explicit-module-boundary-types': 'off',
            '@typescript-eslint/indent': 'off',
            '@typescript-eslint/init-declarations': 'off',
            '@typescript-eslint/key-spacing': 'off',
            '@typescript-eslint/keyword-spacing': 'off',
            '@typescript-eslint/lines-around-comment': 'off',
            '@typescript-eslint/max-params': 'off',
            '@typescript-eslint/member-ordering': 'off',
            '@typescript-eslint/naming-convention': 'off',
            '@typescript-eslint/no-extra-parens': 'off',
            '@typescript-eslint/no-extraneous-class': [
                'error',
                { allowStaticOnly: true },
            ],
            '@typescript-eslint/no-magic-numbers': 'off',
            '@typescript-eslint/no-misused-spread': [
                'error',
                { allow: [{ from: 'lib', name: 'string' }] },
            ],
            '@typescript-eslint/no-shadow': 'off',
            '@typescript-eslint/no-unnecessary-type-conversion': 'off',
            '@typescript-eslint/no-unnecessary-type-parameters': 'off',
            '@typescript-eslint/no-unsafe-enum-comparison': 'off',
            '@typescript-eslint/no-unsafe-type-assertion': 'off',
            '@typescript-eslint/no-unused-vars': [
                'warn',
                { argsIgnorePattern: '^_+$', varsIgnorePattern: '^_+$' },
            ],
            '@typescript-eslint/non-nullable-type-assertion-style': 'off',
            '@typescript-eslint/object-curly-spacing': 'off',
            '@typescript-eslint/padding-line-between-statements': 'off',
            '@typescript-eslint/prefer-destructuring': 'off',
            '@typescript-eslint/prefer-readonly-parameter-types': 'off',
            '@typescript-eslint/prefer-regexp-exec': 'off',
            '@typescript-eslint/restrict-template-expressions': 'off',
            '@typescript-eslint/space-before-blocks': 'off',
            '@typescript-eslint/space-before-function-paren': 'off',
            '@typescript-eslint/strict-boolean-expressions': 'off',
            '@typescript-eslint/type-annotation-spacing': 'off',
            'arrow-body-style': ['error', 'always'],
            'capitalized-comments': 'off',
            'class-methods-use-this': 'off',
            complexity: 'off',
            'id-length': 'off',
            'init-declarations': 'off',
            'max-classes-per-file': 'off',
            'max-depth': 'off',
            'max-len': 'off',
            'max-lines': 'off',
            'max-lines-per-function': 'off',
            'max-nested-callbacks': 'off',
            'max-params': 'off',
            'max-statements': 'off',
            'max-statements-per-line': 'error',
            'new-cap': 'off',
            'no-bitwise': 'off',
            'no-case-declarations': 'off',
            'no-console': 'off',
            'no-continue': 'off',
            'no-duplicate-imports': 'off',
            'no-fallthrough': 'off',
            'no-inline-comments': 'off',
            'no-labels': 'off',
            'no-negated-condition': 'off',
            'no-nested-ternary': 'off',
            'no-shadow': 'off',
            'no-ternary': 'off',
            'no-undefined': 'off',
            'no-unused-vars': 'off',
            'no-useless-assignment': 'off',
            'no-warning-comments': 'off',
            'one-var': ['error', { initialized: 'never' }],
            'prefer-destructuring': 'off',
            'prefer-exponentiation-operator': 'off',
            'react/destructuring-assignment': ['error', 'never'],
            'react/forbid-component-props': 'off',
            'react/function-component-definition': [
                'error',
                {
                    namedComponents: 'arrow-function',
                    unnamedComponents: 'arrow-function',
                },
            ],
            'react/jsx-boolean-value': ['error', 'always'],
            'react/jsx-closing-tag-location': 'off',
            'react/jsx-curly-brace-presence': [
                'error',
                {
                    children: 'ignore',
                    propElementValues: 'always',
                    props: 'never',
                },
            ],
            'react/jsx-filename-extension': [
                'error',
                { allow: 'as-needed', extensions: ['.tsx', '.jsx'] },
            ],
            'react/jsx-handler-names': 'off',
            'react/jsx-indent': 'off',
            'react/jsx-indent-props': 'off',
            'react/jsx-max-depth': 'off',
            'react/jsx-max-props-per-line': 'off',
            'react/jsx-newline': 'off',
            'react/jsx-no-bind': 'off',
            'react/jsx-no-literals': 'off',
            'react/jsx-no-useless-fragment': [
                'warn',
                { allowExpressions: true },
            ],
            'react/jsx-one-expression-per-line': 'off',
            'react/jsx-props-no-spreading': 'off',
            'react/jsx-sort-props': [
                'warn',
                {
                    callbacksLast: true,
                    reservedFirst: true,
                    shorthandFirst: true,
                },
            ],
            'react/no-array-index-key': 'off',
            'react/no-multi-comp': 'off',
            'react/no-set-state': 'off',
            'react/react-in-jsx-scope': 'off',
            'react/require-default-props': 'off',
            'react/require-optimization': 'off',
            'require-unicode-regexp': 'off',
            'sort-imports': 'off',
            'sort-keys': ['warn', 'asc', { natural: true }],
            'sort-keys-fix/sort-keys-fix': ['warn', 'asc', { natural: true }],
        },
        settings: { react: { version: 'detect' } },
    },
]);
