customCommands:
  - key: "M"
    command: "git mergetool {{ .SelectedFile.Name }}"
    context: "files"
    loadingText: "opening git mergetool"
    subprocess: true
gui:
  showFileTree: false
  showCommandLog: false
  showBottomLine: false
  expandFocusedSidePanel: true
  showBranchCommitHash: true
  expandedSidePanelWeight: 16
git:
  log:
    showGraph: 'always'
