customCommands:
  - key: "M"
    command: "git mergetool {{ .SelectedFile.Name }}"
    context: "files"
    loadingText: "opening git mergetool"
    output: terminal
gui:
  showFileTree: false
  showCommandLog: false
  showBottomLine: false
  expandFocusedSidePanel: true
  showBranchCommitHash: true
  expandedSidePanelWeight: 3
  showNumstatInFilesView: true
  useHunkModeInStagingView: false
git:
  log:
    showGraph: 'always'
  #pagers:
    #- colorArg: always
      #pager: delta --paging=never --line-numbers
  autoForwardBranches: none
os:
  editPreset: 'nvim'
  edit: 'nvr -l --remote {{filename}}'
