gui:
  showFileTree: false
  showCommandLog: false
  showBottomLine: false
  expandFocusedSidePanel: true
  showBranchCommitHash: true
  expandedSidePanelWeight: 33
git:
  log:
    showGraph: 'always'
